slaps = [
'Windows 95',
'a KFC mega bucket',
'a Jackie Chan Legs .....',
'a pen',
'a shoe',
'a used Tissue Paper',
'a dildo',
'Simpsons creator Matt Groening',
'coca-cola',
'1GB of RAM',
'an ethiopian',
'a pan',
'himself',
'his portable DVD player',
'an ACER T180 MODEL Computer',
'jesus',
'a ban stick',
'a Samosa Tray',
'a Smorgasbord',
'Tarantism',
'A Case Full Of Beers',
'a Barracuda',
'a space monkey',
'his Random Slap Script By SreeKanth',
'a mexican midget',
'the Mexican border',
'a rubber chicken',
'teh ban hammah',
'Bill Gates',
'microsoft',
"STD'S",
'His pan cake',
'a Tooth Pin',
'king leonidas',
'a Jewish rabbi. Double prawned.',
'teh Jew claw',
'Feudalism',
'the modern world',
'a Stinking Socks',
'a he/she',
'-h',
'+q',
"teh 1930's",
'a trojan',
'a trojan condom',
'teh virus',
'teh internetz',
'johnny quest',
'hearts',
'the queen of England',
'crumpets',
'biscuits',
'tea Cup',
'a Used Tooth Brush',
'a Toilet Cleaner Broom',
'his torren underwear',
'drums',
'Paragon chappal',
'Wipped tissues',
'Drum Sticks',
'Girls sandals'
]
